import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [uploading, setUploading] = useState(false);
  const [sharedFiles, setSHaredFiles] = useState([]);
  const [file, setFile] = useState();

  const handleChange = (e) => {
    setFile(e.target.files[0]);
    console.log(e.target.files[0]);
  };

  const upload = async () => {
    if (!file) return alert("select a file first!");
    setUploading(true);
    try {
      const formdata = new FormData();
      formdata.append("inputFile", file);
      const res = await axios.post(
        "http://192.168.43.17:8082/api/upload",
        formdata,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );
      setFile();
      getSharedFileNames();
    } catch (error) {
      alert("Something went wrong!");
      console.log(`Err in uploading file: ${error}`);
    }
    setUploading(false);
  };

  const getSharedFileNames = async () => {
    try {
      const res = await axios.get("http://192.168.43.17:8082/api/sharedFiles");
      setSHaredFiles(res.data.files);
    } catch (error) {
      alert("Something went wrong!");
      console.log(`Err in getting shared file names file: ${error}`);
    }
  };

  useEffect(() => {
    getSharedFileNames();
  });

  function DownloadComp({ name }) {
    return (
      <>
        <div style={{ display: "flex", alignItems: "center" }}>
          <p style={{ marginRight: "10px" }}>{name}</p>
          <a href={`http://192.168.43.17:8082/api/download/${name}`}>
            <button>download</button>
          </a>
        </div>
        <br />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Want to upload something to pc?</h1>
        <div>
          <input type="file" onChange={handleChange} />
          {uploading ? (
            <p>uploading...</p>
          ) : (
            <button onClick={upload}>Upload</button>
          )}
        </div>
        <br />
        <br />
        <h1>Want to download something from the pc?</h1>
        <br />
        {sharedFiles.map((filename, index) => {
          return <DownloadComp key={index} name={filename} />;
        })}
      </main>
    </>
  );
}
